config/routes.rb
Rails.application.routes.draw do

  root to: 'products#index'

  resources :products, only: [:index, :show]
  resources :categories, only: [:show]

  resource :cart, only: [:show] do
    post   :add_item
    post   :remove_item
  end

  resources :orders, only: [:create, :show]

  namespace :admin do
    root to: 'dashboard#show'
    resources :products, except: [:edit, :update, :show]
    resources :categories, except: [:edit, :update, :show]
  end
  
  resources :users, only: [:new, :create, :destroy] do
    get 'login', on: :collection
    post 'authenticate', on: :collection
    delete 'logout', on: :collection
  end 

  get '/about', to: 'about#index'

end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :email, presence: true, uniqueness: { case_sensitive: false }
  validates :password, length: { minimum: 6 }, allow_nil: true

  before_validation :downcase_email

  def self.authenticate_with_credentials(email, password)
    user = User.find_by('LOWER(email) = ?', email.downcase.strip) if email.present?
    user if user&.authenticate(password)
  end

  private

  def downcase_email
    self.email = email.downcase.strip if email.present?
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      redirect_to root_path, notice: 'Registered and logged in successfully!'
    else
      render 'new'
    end
  end

  def login
    # Display login form
  end

  def authenticate
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to root_path, notice: 'Logged in successfully!'
    else
      flash.now[:danger] = user ? 'Invalid password' : 'User not found'
      render 'login'
    end
  end

  def logout
    log_out
    redirect_to root_path, notice: 'Logged out successfully!'
  end

  private

  def log_in(user)
    session[:user_id] = user.id
  end

  def log_out
    session.delete(:user_id)
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation)
  end
end

app/views/users/login.html.erb
<% if flash[:danger] %>
  <div class="alert alert-danger">
    <%= flash[:danger] %>
  </div>
<% end %>
<br/>
<h1>Login</h1>
<br/>
<%= form_with(url: authenticate_users_path, method: :post) do |form| %>
  <%= form.label :email %>
  <%= form.email_field :email, name: 'session[email]' %>

  <%= form.label :password %>
  <%= form.password_field :password, name: 'session[password]' %>

  <%= form.submit 'Login' %>
<% end %>

app/views/users/new.html.erb
<div class="user_signup form-group">
  <h1>Sign Up</h1>
  <%= form_with(model: @user, url: users_path) do |form| %>
    <table>
      <tr>
        <td>
        <%= form.label :first_name %>
        </td>
        <td>
        <%= form.text_field :first_name, class: 'form-control' %>
        </td>
      </tr>
      <tr>
        <td>
        <%= form.label :last_name %>
        </td>
        <td>
        <%= form.text_field :last_name, class: 'form-control' %>
        </td>
      </tr>
      <tr>
        <td>
        <%= form.label :email %>
        </td>
        <td>
        <%= form.email_field :email, class: 'form-control' %>
       </td>
      </tr>
      <tr>
        <td>
        <%= form.label :password %>
        </td>
        <td>
        <%= form.password_field :password, class: 'form-control' %>
        </td>
      </tr>
      <tr>
        <td>
        <%= form.label :password_confirmation %>
        </td>
        <td>
        <%= form.password_field :password_confirmation, class: 'form-control' %>
        </td>
      </tr>
      <tr>
        <td colspan="2">
        <%= form.submit 'Sign Up', class: 'btn btn-primary' %>
        </td>
      </tr>
    </table>
  </form>
</div>
<% end %>

app/views/users/show.html.erb
<h1>Welcome, <%= @user.first_name %></h1>
<p>Email: <%= @user.email %></p>

<%= link_to 'Logout', logout_users_path, method: :delete %>